version: 0.2

phases:
  install:
    commands:
      - echo "Nothing to install in this simple build."

  pre_build:
    commands:


      # Create group
      - echo "Createing the group"
      - aws iam create-group --group-name Mahi

       # Attach full S3 access policy to the group
      - echo "Attaching S3 FullAccess Policy to group"
      - aws iam attach-group-policy --group-name mahi --policy-arn arn:aws:iam::aws:policy/AmazonS3FullAccess
      
      - echo "Preparing for build."

  build:
    commands:
      - echo "Building project... (In this case, no build is needed for static HTML)."
      
      # Create IAM user
      - echo "Creating IAM user"
      - aws iam create-user --user-name mohanish

    

      # Add the user to the group
      - echo "Adding IAM user to the group"
      - aws iam add-user-to-group --user-name mohanish --group-name mahi
      

      # Create S3 bucket
      - echo "Creating S3 bucket"
      - aws s3api create-bucket --bucket mahi1997619 --region ap-south-1 --create-bucket-configuration LocationConstraint=ap-south-1

  post_build:
    commands:
      
      # Delete the IAM user
      - echo "Deleting IAM user"
      - aws iam remove-user-from-group --user-name mohanish --group-name mahi
      - aws iam delete-user --user-name mohanish

      - echo "Build completed!"

artifacts:
  files:
    - '**/*'  # Specify the file you want to store as an artifact
